language: java

jdk:
 - oraclejdk8
 
addons:
 apt:
  packages:
   - oracle-java8-installer

# add this if you want to be notified about successfull/failed builds to your mail.
notifications:
 email:
  - smart.market.cs@gmail.com 

# add this if you use maven for your project and want to verify mvn build is successful and all unit tests pass.
script:
 - mvn clean install -DskipTests=false
 - mvn cobertura:cobertura

# running coverage tool
after_success:
  - bash <(curl -s https://codecov.io/bash)
