codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "30...100"
  status:
    project: off
    patch: off

  ignore: 
   - Employee/src/main/java/EmployeeGui/
   - Employee/src/main/java/EmployeeDefs/
   - Common/src/main/java/SMExceptions
   - Common/src/main/java/GuiUtils
   - Common/src/main/java/CommonDefs

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
