coverage:
  ignore: 
     - "Employee/src/main/java/EmployeeGui/"
     - "Employee/src/main/java/EmployeeDefs/"
     - "Common/src/main/java/SMExceptions/"
     - "Common/src/main/java/GuiUtils/"
     - "Common/src/main/java/CommonDefs/"
     - "Common/src/main/java/ClientServerApi/ClientServerDefs.java"
     - "Common/src/main/java/ClientServerApi/ResultDescriptor.java"
     - "Common/src/main/java/ClientServerApi/CommandDescriptor.java"
     - "Common/src/main/java/UtilsImplementations/"
     - "Customer/src/main/java/CustomerGuiHelpers/"
     - "Customer/src/main/java/CustomerGuiScreens/"
