codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: up
  range: "30...100"
  status:
    project:
      default:
        enabled: no
        target: auto
    changes: no

# Don't post a comment on pull requests.
comment: off

  ignore: 
   - Employee/src/main/java/EmployeeGui/
   - Employee/src/main/java/EmployeeDefs/
   - Common/src/main/java/SMExceptions
   - Common/src/main/java/GuiUtils
   - Common/src/main/java/CommonDefs
   - Cart/src/main/java/CartGuiHelpers/
   - Cart/src/main/java/CartGuiScreens/
   - Server/src/main/java/ServerRunner/Main.java
   - Server/src/main/java/SQLDatabase/SQLDatabaseStrings.java

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
